services:
  app:
    build: .
    develop:
      watch:
        - action: sync
          path: src/main/resources/
          target: /app/src/main/resources/
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db
      SPRING_DATASOURCE_USERNAME: db_user
      SPRING_DATASOURCE_PASSWORD: db_password
    depends_on:
      db:
        condition: service_healthy

  spy:
    build: .
    environment:
      API_URL: http://localhost:8080/
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db
      SPRING_DATASOURCE_USERNAME: db_user
      SPRING_DATASOURCE_PASSWORD: db_password
    ports:
      - 8081:8080
    depends_on:
      - app

  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user -d db"]
      interval: 10s
      timeout: 5s
      retries: 5
